version: "3"

services:
  app:
    container_name: paymentautoaudit
    restart: always
    build:
      context: .
    ports:
      - "8001:8000"
    volumes:
      - ./app:/app
    command:
      sh -c "mkdir -p logs media &&
             python manage.py runserver 0.0.0.0:8000"
    networks:
      - mvrinsights_mvr-network
networks:
  mvrinsights_mvr-network:
    external: true
