# Generated by Django 3.0.4 on 2020-04-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20200330_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type9',
            fields=[
                ('transaction_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(null=True)),
                ('mobile', models.CharField(max_length=10)),
                ('consumer', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=30)),
                ('mode', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=100)),
                ('tip', models.CharField(max_length=100)),
                ('cash_at_pos', models.CharField(max_length=250)),
                ('transaction_type', models.CharField(max_length=250)),
                ('auth_code', models.CharField(max_length=100)),
                ('card', models.CharField(max_length=100)),
                ('card_type', models.CharField(max_length=100)),
                ('brand_type', models.CharField(max_length=200)),
                ('card_transaction_type', models.CharField(max_length=200)),
                ('rrn', models.CharField(max_length=200)),
                ('device_serial', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('settle_on', models.DateTimeField(null=True)),
                ('mid', models.CharField(max_length=250)),
                ('tid', models.CharField(max_length=300)),
                ('batch', models.CharField(max_length=500)),
                ('ref', models.CharField(max_length=100)),
                ('payer', models.CharField(max_length=100)),
                ('tid_location', models.CharField(max_length=150)),
                ('dx_mode', models.CharField(max_length=200)),
                ('acquiring_bank', models.CharField(max_length=200)),
            ],
        ),
    ]
