# Generated by Django 3.0.4 on 2020-04-09 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_auto_20200409_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type9',
            old_name='settle_on',
            new_name='settled_on',
        ),
    ]
