# Generated by Django 3.0.4 on 2020-04-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_auto_20200409_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='type9',
            name='invoice',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
