# Generated by Django 3.0.4 on 2020-04-10 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_type9_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type9',
            old_name='transaction_id',
            new_name='id',
        ),
    ]
