# Generated by Django 3.0.4 on 2020-04-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0009_auto_20200410_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type9',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
