# Generated by Django 3.0.4 on 2020-04-10 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0010_auto_20200410_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type9',
            old_name='card_transaction_type',
            new_name='card_txn_type',
        ),
        migrations.RenameField(
            model_name='type9',
            old_name='transaction_type',
            new_name='txn_type',
        ),
    ]
