# Generated by Django 3.0.4 on 2020-04-29 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0012_cashentry_customer_customercheckin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_name',
            new_name='name',
        ),
    ]
