# Generated by Django 3.0.4 on 2020-05-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0014_auto_20200511_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='type9',
            field=models.ManyToManyField(related_name='linked_customer', to='upload.Type9'),
        ),
    ]
